local types = {
  DEFAULT_PORT = 9999,
  DEFAULT_TRANSITION_TIME = 400,
  MAX_HUE = 360,
  MAX_SAT = 100,
  MAX_BRIGHTNESS = 100,
  MIN_KELVIN = 2500,
  MAX_KELVIN = 9000,
  SMARTBULB = "IOT.SMARTBULB",
  SMARTPLUGSWITCH = "IOT.SMARTPLUGSWITCH"
}

return types
